modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
#mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/TheAGamePlayer/The-Pure-Suffering-Mod/issues" #optional
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/TheAGamePlayer/The-Pure-Suffering-Mod/main/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-pure-suffering-mod" #optional
logoFile="puresuffering.png" #optional
credits="Thanks to the NeoForge Team for making this possible!" #optional
authors="${mod_authors}" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
#(multi line!) (#mandatory)
description='''${mod_description}'''
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[mixins]]
config="puresuffering.mixins.json"
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
